package deviantart

type Country struct {
	CountryID uint8  `json:"countryid"`
	Name      string `json:"name"`
}

// Countries is a saved list of countries.
//
// Feel free to report the issue if country list was changed ;)
var Countries = []Country{
	{CountryID: 1, Name: "United States"},
	{CountryID: 2, Name: "Canada"},
	{CountryID: 3, Name: "Afghanistan"},
	{CountryID: 242, Name: "Åland Islands"},
	{CountryID: 4, Name: "Albania"},
	{CountryID: 5, Name: "Algeria"},
	{CountryID: 6, Name: "American Samoa"},
	{CountryID: 7, Name: "Andorra"},
	{CountryID: 8, Name: "Angola"},
	{CountryID: 9, Name: "Anguilla"},
	{CountryID: 10, Name: "Antarctica"},
	{CountryID: 11, Name: "Antigua and Barbuda"},
	{CountryID: 12, Name: "Argentina"},
	{CountryID: 13, Name: "Armenia"},
	{CountryID: 14, Name: "Aruba"},
	{CountryID: 15, Name: "Australia"},
	{CountryID: 16, Name: "Austria"},
	{CountryID: 17, Name: "Azerbaijan"},
	{CountryID: 18, Name: "The Bahamas"},
	{CountryID: 19, Name: "Bahrain"},
	{CountryID: 20, Name: "Bangladesh"},
	{CountryID: 21, Name: "Barbados"},
	{CountryID: 22, Name: "Belarus"},
	{CountryID: 23, Name: "Belgium"},
	{CountryID: 24, Name: "Belize"},
	{CountryID: 25, Name: "Benin"},
	{CountryID: 26, Name: "Bermuda"},
	{CountryID: 27, Name: "Bhutan"},
	{CountryID: 28, Name: "Bolivia"},
	{CountryID: 29, Name: "Bosnia and Herzegovina"},
	{CountryID: 30, Name: "Botswana"},
	{CountryID: 31, Name: "Bouvet Island"},
	{CountryID: 32, Name: "Brazil"},
	{CountryID: 33, Name: "British Indian Ocean Territory"},
	{CountryID: 35, Name: "Brunei"},
	{CountryID: 36, Name: "Bulgaria"},
	{CountryID: 37, Name: "Burkina Faso"},
	{CountryID: 38, Name: "Burundi"},
	{CountryID: 39, Name: "Cambodia"},
	{CountryID: 40, Name: "Cameroon"},
	{CountryID: 41, Name: "Cape Verde"},
	{CountryID: 42, Name: "Cayman Islands"},
	{CountryID: 43, Name: "Central African Republic"},
	{CountryID: 44, Name: "Chad"},
	{CountryID: 45, Name: "Chile"},
	{CountryID: 46, Name: "People's Republic of China"},
	{CountryID: 47, Name: "Christmas Island"},
	{CountryID: 48, Name: "Cocos (Keeling) Islands"},
	{CountryID: 49, Name: "Colombia"},
	{CountryID: 50, Name: "Comoros"},
	{CountryID: 235, Name: "Democratic Republic of the Congo"},
	{CountryID: 51, Name: "Republic of the Congo"},
	{CountryID: 52, Name: "Cook Islands"},
	{CountryID: 53, Name: "Costa Rica"},
	{CountryID: 106, Name: "Côte d'Ivoire"},
	{CountryID: 54, Name: "Croatia"},
	{CountryID: 55, Name: "Cuba"},
	{CountryID: 56, Name: "Cyprus"},
	{CountryID: 57, Name: "Czech Republic"},
	{CountryID: 58, Name: "Denmark"},
	{CountryID: 59, Name: "Djibouti"},
	{CountryID: 60, Name: "Dominica"},
	{CountryID: 61, Name: "Dominican Republic"},
	{CountryID: 62, Name: "East Timor"},
	{CountryID: 63, Name: "Ecuador"},
	{CountryID: 64, Name: "Egypt"},
	{CountryID: 65, Name: "El Salvador"},
	{CountryID: 66, Name: "Equatorial Guinea"},
	{CountryID: 67, Name: "Eritrea"},
	{CountryID: 68, Name: "Estonia"},
	{CountryID: 69, Name: "Ethiopia"},
	{CountryID: 70, Name: "Falkland Islands"},
	{CountryID: 71, Name: "Faroe Islands"},
	{CountryID: 72, Name: "Fiji"},
	{CountryID: 73, Name: "Finland"},
	{CountryID: 74, Name: "France"},
	{CountryID: 75, Name: "French Guiana"},
	{CountryID: 76, Name: "French Polynesia"},
	{CountryID: 77, Name: "French Southern Territories"},
	{CountryID: 78, Name: "Gabon"},
	{CountryID: 79, Name: "Gambia"},
	{CountryID: 80, Name: "Georgia"},
	{CountryID: 81, Name: "Germany"},
	{CountryID: 82, Name: "Ghana"},
	{CountryID: 83, Name: "Gibraltar"},
	{CountryID: 84, Name: "Greece"},
	{CountryID: 85, Name: "Greenland"},
	{CountryID: 86, Name: "Grenada"},
	{CountryID: 87, Name: "Guadeloupe"},
	{CountryID: 88, Name: "Guam"},
	{CountryID: 89, Name: "Guatemala"},
	{CountryID: 243, Name: "Guernsey"},
	{CountryID: 90, Name: "Guinea"},
	{CountryID: 91, Name: "Guinea-Bissau"},
	{CountryID: 92, Name: "Guyana"},
	{CountryID: 93, Name: "Haiti"},
	{CountryID: 94, Name: "Heard Island and McDonald Islands"},
	{CountryID: 95, Name: "Honduras"},
	{CountryID: 96, Name: "Hong Kong"},
	{CountryID: 97, Name: "Hungary"},
	{CountryID: 98, Name: "Iceland"},
	{CountryID: 99, Name: "India"},
	{CountryID: 100, Name: "Indonesia"},
	{CountryID: 101, Name: "Iran"},
	{CountryID: 102, Name: "Iraq"},
	{CountryID: 103, Name: "Ireland"},
	{CountryID: 244, Name: "Isle of Man"},
	{CountryID: 104, Name: "Israel"},
	{CountryID: 105, Name: "Italy"},
	{CountryID: 107, Name: "Jamaica"},
	{CountryID: 108, Name: "Japan"},
	{CountryID: 245, Name: "Jersey"},
	{CountryID: 109, Name: "Jordan"},
	{CountryID: 110, Name: "Kazakhstan"},
	{CountryID: 111, Name: "Kenya"},
	{CountryID: 112, Name: "Kiribati"},
	{CountryID: 113, Name: "North Korea"},
	{CountryID: 114, Name: "South Korea"},
	{CountryID: 115, Name: "Kuwait"},
	{CountryID: 116, Name: "Kyrgyzstan"},
	{CountryID: 117, Name: "Laos"},
	{CountryID: 118, Name: "Latvia"},
	{CountryID: 119, Name: "Lebanon"},
	{CountryID: 120, Name: "Lesotho"},
	{CountryID: 121, Name: "Liberia"},
	{CountryID: 122, Name: "Libya"},
	{CountryID: 123, Name: "Liechtenstein"},
	{CountryID: 124, Name: "Lithuania"},
	{CountryID: 125, Name: "Luxembourg"},
	{CountryID: 126, Name: "Macau"},
	{CountryID: 127, Name: "Macedonia"},
	{CountryID: 128, Name: "Madagascar"},
	{CountryID: 129, Name: "Malawi"},
	{CountryID: 130, Name: "Malaysia"},
	{CountryID: 131, Name: "Maldives"},
	{CountryID: 132, Name: "Mali"},
	{CountryID: 133, Name: "Malta"},
	{CountryID: 134, Name: "Marshall Islands"},
	{CountryID: 135, Name: "Martinique"},
	{CountryID: 136, Name: "Mauritania"},
	{CountryID: 137, Name: "Mauritius"},
	{CountryID: 138, Name: "Mayotte"},
	{CountryID: 139, Name: "Mexico"},
	{CountryID: 140, Name: "Micronesia"},
	{CountryID: 141, Name: "Moldova"},
	{CountryID: 142, Name: "Monaco"},
	{CountryID: 143, Name: "Mongolia"},
	{CountryID: 241, Name: "Montenegro"},
	{CountryID: 144, Name: "Montserrat"},
	{CountryID: 145, Name: "Morocco"},
	{CountryID: 146, Name: "Mozambique"},
	{CountryID: 147, Name: "Myanmar"},
	{CountryID: 148, Name: "Namibia"},
	{CountryID: 149, Name: "Nauru"},
	{CountryID: 150, Name: "Nepal"},
	{CountryID: 151, Name: "Netherlands"},
	{CountryID: 152, Name: "Netherlands Antilles"},
	{CountryID: 153, Name: "New Caledonia"},
	{CountryID: 154, Name: "New Zealand"},
	{CountryID: 155, Name: "Nicaragua"},
	{CountryID: 156, Name: "Niger"},
	{CountryID: 157, Name: "Nigeria"},
	{CountryID: 158, Name: "Niue"},
	{CountryID: 159, Name: "Norfolk Island"},
	{CountryID: 160, Name: "Northern Mariana Islands"},
	{CountryID: 161, Name: "Norway"},
	{CountryID: 162, Name: "Oman"},
	{CountryID: 163, Name: "Pakistan"},
	{CountryID: 164, Name: "Palau"},
	{CountryID: 165, Name: "Panama"},
	{CountryID: 166, Name: "Papua New Guinea"},
	{CountryID: 167, Name: "Paraguay"},
	{CountryID: 168, Name: "Peru"},
	{CountryID: 169, Name: "Philippines"},
	{CountryID: 170, Name: "Pitcairn Islands"},
	{CountryID: 171, Name: "Poland"},
	{CountryID: 172, Name: "Portugal"},
	{CountryID: 173, Name: "Puerto Rico"},
	{CountryID: 174, Name: "Qatar"},
	{CountryID: 175, Name: "Réunion"},
	{CountryID: 176, Name: "Romania"},
	{CountryID: 177, Name: "Russia"},
	{CountryID: 178, Name: "Rwanda"},
	{CountryID: 197, Name: "Saint Helena"},
	{CountryID: 180, Name: "Saint Kitts and Nevis"},
	{CountryID: 181, Name: "Saint Lucia"},
	{CountryID: 198, Name: "Saint Pierre and Miquelon"},
	{CountryID: 182, Name: "Saint Vincent and the Grenadines"},
	{CountryID: 183, Name: "Samoa"},
	{CountryID: 184, Name: "San Marino"},
	{CountryID: 185, Name: "São Tomé and Príncipel"},
	{CountryID: 186, Name: "Saudi Arabia"},
	{CountryID: 187, Name: "Senegal"},
	{CountryID: 234, Name: "Serbia"},
	{CountryID: 188, Name: "Seychelles"},
	{CountryID: 189, Name: "Sierra Leone"},
	{CountryID: 190, Name: "Singapore"},
	{CountryID: 191, Name: "Slovakia"},
	{CountryID: 192, Name: "Slovenia"},
	{CountryID: 238, Name: "Solomon Islands"},
	{CountryID: 193, Name: "Somalia"},
	{CountryID: 194, Name: "South Africa"},
	{CountryID: 179, Name: "South Georgia & S. Sandwich Islands"},
	{CountryID: 195, Name: "Spain"},
	{CountryID: 196, Name: "Sri Lanka"},
	{CountryID: 199, Name: "Sudan"},
	{CountryID: 200, Name: "Suriname"},
	{CountryID: 239, Name: "Svalbard"},
	{CountryID: 202, Name: "Swaziland"},
	{CountryID: 203, Name: "Sweden"},
	{CountryID: 204, Name: "Switzerland"},
	{CountryID: 205, Name: "Syria"},
	{CountryID: 206, Name: "Taiwan"},
	{CountryID: 207, Name: "Tajikistan"},
	{CountryID: 208, Name: "Tanzania"},
	{CountryID: 209, Name: "Thailand"},
	{CountryID: 210, Name: "Togo"},
	{CountryID: 211, Name: "Tokelau"},
	{CountryID: 212, Name: "Tonga"},
	{CountryID: 213, Name: "Trinidad and Tobago"},
	{CountryID: 214, Name: "Tunisia"},
	{CountryID: 215, Name: "Turkey"},
	{CountryID: 216, Name: "Turkmenistan"},
	{CountryID: 217, Name: "Turks and Caicos Islands"},
	{CountryID: 218, Name: "Tuvalu"},
	{CountryID: 220, Name: "Uganda"},
	{CountryID: 221, Name: "Ukraine"},
	{CountryID: 222, Name: "United Arab Emirates"},
	{CountryID: 223, Name: "United Kingdom"},
	{CountryID: 219, Name: "United States Minor Outlying Islands"},
	{CountryID: 224, Name: "Uruguay"},
	{CountryID: 225, Name: "Uzbekistan"},
	{CountryID: 226, Name: "Vanuatu"},
	{CountryID: 227, Name: "Vatican City"},
	{CountryID: 228, Name: "Venezuela"},
	{CountryID: 229, Name: "Vietnam"},
	{CountryID: 34, Name: "British Virgin Islands"},
	{CountryID: 230, Name: "United States Virgin Islands"},
	{CountryID: 231, Name: "Wallis and Futuna"},
	{CountryID: 232, Name: "Western Sahara"},
	{CountryID: 233, Name: "Yemen"},
	{CountryID: 236, Name: "Zambia"},
	{CountryID: 237, Name: "Zimbabwe"},
}
